# Generated by Django 4.2.6 on 2023-10-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
            ],
        ),
    ]
